import Navbar from '@/components/Navbar'
import './globals.css'
import { Inter } from 'next/font/google'
import Footer from '@/components/Footer'
import BotonFlotante from '@/components/BotonFlotante'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Shop From',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en" data-theme="light">
      <body>
      <div className='text-center pt-3 pb-4 bg bg-[rgb(0,23,79)]'>
                <span className='text-white text-xs'>¡Feliz Día del Padre!- Hasta 40% de dscto.</span>
            </div>
      <Navbar/>
        <div>
          {children}
        </div>
      <BotonFlotante/>
      <Footer/> 
      </body>
    </html>
  )
}
